CMON-86 re-add tests lost in CMON-84

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -104,13 +104,27 @@ if [[ -n "$opt_test_pattern" ]]; then
     echo "# Running filtered set of test files: $test_files"
 fi
 
-if [ "global" == $(zonename) ]; then
-    $TOP/node/bin/node ./node_modules/tape/bin/tape $test_files \
-        | tee $OUTPUT_DIR/cmon-agent.tap
-else
-    node ./node_modules/tape/bin/tape $test_files \
-        | tee $OUTPUT_DIR/cmon-agent.tap
-fi
+failed_tests=0
+failed_test_names=
+NODE=node
+set +o errexit
+set -o pipefail
+for t in ${test_files}; do
+    if [ "global" == $(zonename) ]; then
+        NODE=$TOP/node/bin/node
+    fi
+    echo "#"
+    echo "# Running Test: ${t}"
+    echo "#"
+    ${NODE} ${t} \
+        | tee -a $OUTPUT_DIR/cmon-agent.tap
+    if [[ $? != 0 ]]; then
+        failed_tests=$((${failed_tests} + 1))
+        failed_test_names="${failed_test_names} ${t}"
+    fi
+done
+set +o pipefail
+set -o errexit
 
 #---- summary
 
@@ -126,12 +140,39 @@ passed=$(grep "^# pass  [0-9]" $OUTPUT_DIR/*.tap | tr -s ' ' | cut -d ' ' -f3 | 
 [[ -z ${passed} ]] && passed=0
 fail=$((${tests} - ${passed}))
 
-echo "# Completed in ${elapsed} seconds."
-echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
-if [[ ${fail} -gt 0 ]]; then
-    echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
+if [[ -t 1 ]]; then
+    # We're on a terminal, so use color
+    COLOR_GREEN="\033[32m"
+    COLOR_RED="\033[31m"
+    COLOR_ORANGE="\033[33m"
+    COLOR_NORMAL="\033[39m"
+else
+    # no terminal, no color
+    COLOR_GREEN=
+    COLOR_RED=
+    COLOR_ORANGE=
+    COLOR_NORMAL=
 fi
-echo ""
+
+# Output the summary
+echo "#"
+echo "# TESTS COMPLETE IN ${elapsed} SECONDS, SUMMARY:"
+echo "#"
+echo -e "#   ${COLOR_GREEN}PASS: ${passed} / ${tests}${COLOR_NORMAL}"
+if [[ ${fail} -gt 0 || ${failed_tests} -gt 0 ]]; then
+    if [[ ${fail} -eq 0 ]]; then
+        # tests failed, but no 'not ok' messages, so probably crashed
+        fail="?"
+    fi
+    echo -e "#   ${COLOR_RED}FAIL: ${fail} / ${tests}${COLOR_NORMAL}"
+    echo "#"
+    echo "# FAILED TESTS:"
+    echo "#"
+    for t in ${failed_test_names}; do
+        echo "#   - ${t}"
+    done
+fi
+echo "#"
 
 if [[ ${tests} != ${passed} ]]; then
     exit 1
